// Code generated by adv-pg. DO NOT EDIT.
//foo:bar
//foo:test

package advpgtest

import (
	"context"
	"database/sql"
	"errors"
	"time"

	advpg "github.com/my-mail-ru/go-adv-pg"
	advpgconn "github.com/my-mail-ru/go-adv-pg/conn"
)

//// User ////

const (
	sqlSelectUser          = `SELECT id, name, type, post_count, created_at, updated_at FROM users`
	sqlInsertUser          = `INSERT INTO users (name, type) VALUES ($1, $2) RETURNING id, post_count, created_at, updated_at`
	sqlFullUpdateUser      = `UPDATE users SET name=$1, type=$2, post_count=post_count+$3`
	sqlUpdateReturningUser = ` RETURNING post_count, updated_at`
	sqlSelectMutatorsUser  = `SELECT post_count FROM users WHERE id=$1`
)

type UserRecord struct {
	updateMask   uint64
	data         User
	mutPostCount int
}

func (data User) Record() *UserRecord {
	return &UserRecord{data: data}
}

func (model *UserRecord) ID() int {
	return model.data.ID
}

func (model *UserRecord) Name() string {
	return model.data.Name
}

func (model *UserRecord) Type() int {
	return model.data.Type
}

func (model *UserRecord) PostCount() int {
	return model.data.PostCount
}

func (model *UserRecord) CreatedAt() time.Time {
	return model.data.CreatedAt
}

func (model *UserRecord) UpdatedAt() time.Time {
	return model.data.UpdatedAt
}

func (model *UserRecord) SetName(x string) {
	model.data.Name = x
	model.updateMask |= 1
}

func (model *UserRecord) SetType(x int) {
	model.data.Type = x
	model.updateMask |= 2
}

func (model *UserRecord) IncPostCount() {
	model.mutPostCount++
}

func (model *UserRecord) DecPostCount() {
	model.mutPostCount--
}

func (model *UserRecord) AddPostCount(x int) {
	model.mutPostCount += x
}

func (*UserRecord) Table() string {
	return "users"
}

type UserDAO struct {
	db advpg.DB
}

func NewUserDAO(db advpg.DB) UserDAO {
	return UserDAO{db: db}
}

func (model *UserRecord) querySelectByID(inID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectUser+` WHERE id=$1`,
		[]any{inID},
		[]any{&model.data.ID, &model.data.Name, &model.data.Type, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt},
	)
}

func (model *UserRecord) queryDeleteByID(inID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM users WHERE id=$1`,
		[]any{inID},
		nil,
	)
}

func (dao UserDAO) SelectByID(ctx context.Context, inID int, optFuncs ...advpg.SelectOptionFunc) (UserRecord, error) {
	var data UserRecord
	q := data.querySelectByID(inID)
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "ID")
	opt := advpg.NewSelectOptions(optFuncs...)
	db := advpgconn.ReplicaByOpt(dao.db, opt, "users")
	row := db.QueryRow(ctx, q.SQL(), q.Args()...)
	err := row.Scan(q.Results()...)

	return data, err
}

func (dao UserDAO) DeleteByID(ctx context.Context, inID int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "ID")
	q := (*UserRecord)(nil).queryDeleteByID(inID)
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

type SelectMultiByIDTypeKey struct {
	ID   int
	Type int
}

func (model *UserRecord) querySelectMultiByIDType(keys []SelectMultiByIDTypeKey) *advpg.QueryBuilder {
	if len(keys) == 0 {
		return &advpg.QueryBuilder{}

	}

	q := advpg.NewQueryBuilder(sqlSelectUser + ` WHERE (id, type) IN (`)

	for i, k := range keys {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.ID)
		q.AppendSQL(", $")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.Type)
		q.AppendSQL(")")
	}

	q.AppendSQL(`) ORDER BY created_at DESC`)
	q.SetResults([]any{&model.data.ID, &model.data.Name, &model.data.Type, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt})

	return q
}

func (model *UserRecord) queryDeleteMultiByIDType(keys []SelectMultiByIDTypeKey) *advpg.QueryBuilder {
	if len(keys) == 0 {
		return &advpg.QueryBuilder{}

	}

	q := advpg.NewQueryBuilder(`DELETE FROM users WHERE (id, type) IN (`)

	for i, k := range keys {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.ID)
		q.AppendSQL(", $")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.Type)
		q.AppendSQL(")")
	}

	q.AppendSQL(`)`)

	return q
}

func (dao UserDAO) SelectMultiByIDType(ctx context.Context, keys []SelectMultiByIDTypeKey, optFuncs ...advpg.SelectOptionFunc) ([]UserRecord, error) {
	var data UserRecord
	q := data.querySelectMultiByIDType(keys)
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "IDType")
	opt := advpg.NewSelectOptions(optFuncs...)
	db := advpgconn.ReplicaByOpt(dao.db, opt, "users")

	rows, err := db.Query(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	ret := ([]UserRecord)(nil)

	for rows.Next() {
		if err = rows.Scan(q.Results()...); err != nil {
			return nil, err
		}

		ret = append(ret, data)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return ret, nil
}

func (dao UserDAO) DeleteMultiByIDType(ctx context.Context, keys []SelectMultiByIDTypeKey) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "IDType")
	q := (*UserRecord)(nil).queryDeleteMultiByIDType(keys)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

func (model *UserRecord) querySelectByName(inName string) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectUser+` WHERE name=$1`,
		[]any{inName},
		[]any{&model.data.ID, &model.data.Name, &model.data.Type, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt},
	)
}

func (model *UserRecord) queryDeleteByName(inName string) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM users WHERE name=$1`,
		[]any{inName},
		nil,
	)
}

func (dao UserDAO) SelectByName(ctx context.Context, inName string, optFuncs ...advpg.SelectOptionFunc) ([]UserRecord, error) {
	var data UserRecord
	q := data.querySelectByName(inName)
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "Name")
	opt := advpg.NewSelectOptions(optFuncs...)
	db := advpgconn.ReplicaByOpt(dao.db, opt, "users")

	rows, err := db.Query(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	ret := ([]UserRecord)(nil)

	for rows.Next() {
		if err = rows.Scan(q.Results()...); err != nil {
			return nil, err
		}

		ret = append(ret, data)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return ret, nil
}

func (dao UserDAO) DeleteByName(ctx context.Context, inName string) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "Name")
	q := (*UserRecord)(nil).queryDeleteByName(inName)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

func (model *UserRecord) queryInsert() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlInsertUser,
		[]any{model.data.Name, model.data.Type},
		[]any{&model.data.ID, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt},
	)
}

func (dao UserDAO) Insert(ctx context.Context, data *UserRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "")
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)

	return err
}

func (model *UserRecord) queryFullUpdate() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlFullUpdateUser+" WHERE id=$4"+sqlUpdateReturningUser,
		[]any{model.data.Name, model.data.Type, model.mutPostCount, model.data.ID},
		[]any{&model.data.PostCount, &model.data.UpdatedAt},
	)
}

func (dao UserDAO) FullUpdate(ctx context.Context, data *UserRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "")
	q := data.queryFullUpdate()
	return dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)
}

func (model *UserRecord) queryUpdate() *advpg.QueryBuilder {
	if model.updateMask == 0 && model.mutPostCount == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE users SET`)
	if model.updateMask&1 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" name=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Name)
	}
	if model.updateMask&2 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" type=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Type)
	}
	if model.mutPostCount != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" post_count=post_count+$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.mutPostCount)
	}
	q.AppendSQL(` WHERE id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.ID)

	q.AppendSQL(sqlUpdateReturningUser)
	q.SetResults([]any{&model.data.PostCount, &model.data.UpdatedAt})

	return q
}

func (model *UserRecord) querySelectMutators() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectMutatorsUser,
		[]any{model.data.ID},
		[]any{&model.data.PostCount},
	)
}

func (model *UserRecord) reset() {
	model.updateMask = 0
	model.mutPostCount = 0
}

func (dao UserDAO) Update(ctx context.Context, data *UserRecord) error {
	q := advpg.Query(data.queryUpdate())
	index := ""
	query := q.SQL()
	if query == "" {
		q = data.querySelectMutators()
		query = q.SQL()
		index = "ID"
	}
	ctx = advpgconn.QueryInfoCtx(ctx, "users", index)

	err := dao.db.QueryRow(ctx, query, q.Args()...).Scan(q.Results()...)
	if err == nil {
		data.reset()
	}

	return err
}

//// ExtLink ////

const (
	sqlSelectExtLink          = `SELECT user_id, ext_id, EXTRACT(EPOCH FROM created_at::TIMESTAMP WITH TIME ZONE)::BIGINT AS created_at, status, link_count FROM ext_links`
	sqlInsertExtLink          = `INSERT INTO ext_links (user_id, ext_id, created_at, status) VALUES ($1, $2, TIMESTAMP WITH TIME ZONE 'epoch' + INTERVAL '1 sec' * $3, $4) ON CONFLICT (user_id, ext_id) DO UPDATE SET status=EXCLUDED.status, link_count=ext_links.link_count+$5 RETURNING link_count`
	sqlFullUpdateExtLink      = `UPDATE ext_links SET status=$1, link_count=link_count+$2`
	sqlUpdateReturningExtLink = ` RETURNING link_count`
	sqlSelectMutatorsExtLink  = `SELECT link_count FROM ext_links WHERE user_id=$1 AND ext_id=$2`
)

type ExtLinkRecord struct {
	updateMask   uint64
	data         ExtLink
	mutLinkCount int
}

func (data ExtLink) Record() *ExtLinkRecord {
	return &ExtLinkRecord{data: data}
}

func (model *ExtLinkRecord) UserID() int {
	return model.data.UserID
}

func (model *ExtLinkRecord) ExternalID() int {
	return model.data.ExternalID
}

func (model *ExtLinkRecord) CreatedAt() MyTime {
	return model.data.CreatedAt
}

func (model *ExtLinkRecord) Status() int {
	return model.data.Status
}

func (model *ExtLinkRecord) LinkCount() int {
	return model.data.LinkCount
}

func (model *ExtLinkRecord) SetUserID(x int) {
	model.data.UserID = x
}

func (model *ExtLinkRecord) SetExternalID(x int) {
	model.data.ExternalID = x
}

func (model *ExtLinkRecord) SetCreatedAt(x MyTime) {
	model.data.CreatedAt = x
}

func (model *ExtLinkRecord) SetStatus(x int) {
	model.data.Status = x
	model.updateMask |= 1
}

func (model *ExtLinkRecord) IncLinkCount() {
	model.mutLinkCount++
}

func (model *ExtLinkRecord) DecLinkCount() {
	model.mutLinkCount--
}

func (model *ExtLinkRecord) AddLinkCount(x int) {
	model.mutLinkCount += x
}

func (*ExtLinkRecord) Table() string {
	return "ext_links"
}

type ExtLinkDAO struct {
	db advpg.DB
}

func NewExtLinkDAO(db advpg.DB) ExtLinkDAO {
	return ExtLinkDAO{db: db}
}

func (model *ExtLinkRecord) querySelectByPrimaryKey(inUserID int, inExternalID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectExtLink+` WHERE user_id=$1 AND ext_id=$2`,
		[]any{inUserID, inExternalID},
		[]any{&model.data.UserID, &model.data.ExternalID, &model.data.CreatedAt, &model.data.Status, &model.data.LinkCount},
	)
}

func (model *ExtLinkRecord) queryDeleteByPrimaryKey(inUserID int, inExternalID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM ext_links WHERE user_id=$1 AND ext_id=$2`,
		[]any{inUserID, inExternalID},
		nil,
	)
}

func (dao ExtLinkDAO) SelectByPrimaryKey(ctx context.Context, inUserID int, inExternalID int, optFuncs ...advpg.SelectOptionFunc) (ExtLinkRecord, error) {
	var data ExtLinkRecord
	q := data.querySelectByPrimaryKey(inUserID, inExternalID)
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "PrimaryKey")
	opt := advpg.NewSelectOptions(optFuncs...)
	db := advpgconn.ReplicaByOpt(dao.db, opt, "ext_links")
	row := db.QueryRow(ctx, q.SQL(), q.Args()...)
	err := row.Scan(q.Results()...)

	return data, err
}

func (dao ExtLinkDAO) DeleteByPrimaryKey(ctx context.Context, inUserID int, inExternalID int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "PrimaryKey")
	q := (*ExtLinkRecord)(nil).queryDeleteByPrimaryKey(inUserID, inExternalID)
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *ExtLinkRecord) querySelectMultiByStatus(inStatuses []int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectExtLink+` WHERE status=IN($1)`,
		[]any{inStatuses},
		[]any{&model.data.UserID, &model.data.ExternalID, &model.data.CreatedAt, &model.data.Status, &model.data.LinkCount},
	)
}

func (model *ExtLinkRecord) queryDeleteMultiByStatus(inStatuses []int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM ext_links WHERE status=IN($1)`,
		[]any{inStatuses},
		nil,
	)
}

func (dao ExtLinkDAO) SelectMultiByStatus(ctx context.Context, inStatuses []int, optFuncs ...advpg.SelectOptionFunc) ([]ExtLinkRecord, error) {
	var data ExtLinkRecord
	q := data.querySelectMultiByStatus(inStatuses)
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "Status")
	opt := advpg.NewSelectOptions(optFuncs...)
	db := advpgconn.ReplicaByOpt(dao.db, opt, "ext_links")

	rows, err := db.Query(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	ret := ([]ExtLinkRecord)(nil)

	for rows.Next() {
		if err = rows.Scan(q.Results()...); err != nil {
			return nil, err
		}

		ret = append(ret, data)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return ret, nil
}

func (dao ExtLinkDAO) DeleteMultiByStatus(ctx context.Context, inStatuses []int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "Status")
	q := (*ExtLinkRecord)(nil).queryDeleteMultiByStatus(inStatuses)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

func (model *ExtLinkRecord) queryInsert() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlInsertExtLink,
		[]any{model.data.UserID, model.data.ExternalID, model.data.CreatedAt, model.data.Status, model.mutLinkCount},
		[]any{&model.data.LinkCount},
	)
}

func (dao ExtLinkDAO) Insert(ctx context.Context, data *ExtLinkRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "")
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)

	return err
}

func (model *ExtLinkRecord) queryFullUpdate() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlFullUpdateExtLink+" WHERE user_id=$3 AND ext_id=$4"+sqlUpdateReturningExtLink,
		[]any{model.data.Status, model.mutLinkCount, model.data.UserID, model.data.ExternalID},
		[]any{&model.data.LinkCount},
	)
}

func (dao ExtLinkDAO) FullUpdate(ctx context.Context, data *ExtLinkRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "")
	q := data.queryFullUpdate()
	return dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)
}

func (model *ExtLinkRecord) queryUpdate() *advpg.QueryBuilder {
	if model.updateMask == 0 && model.mutLinkCount == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE ext_links SET`)
	if model.updateMask&1 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" status=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Status)
	}
	if model.mutLinkCount != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" link_count=link_count+$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.mutLinkCount)
	}
	q.AppendSQL(` WHERE user_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.UserID)
	q.AppendSQL(` AND ext_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.ExternalID)

	q.AppendSQL(sqlUpdateReturningExtLink)
	q.SetResults([]any{&model.data.LinkCount})

	return q
}

func (model *ExtLinkRecord) querySelectMutators() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectMutatorsExtLink,
		[]any{model.data.UserID, model.data.ExternalID},
		[]any{&model.data.LinkCount},
	)
}

func (model *ExtLinkRecord) reset() {
	model.updateMask = 0
	model.mutLinkCount = 0
}

func (dao ExtLinkDAO) Update(ctx context.Context, data *ExtLinkRecord) error {
	q := advpg.Query(data.queryUpdate())
	index := ""
	query := q.SQL()
	if query == "" {
		q = data.querySelectMutators()
		query = q.SQL()
		index = "PrimaryKey"
	}
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", index)

	err := dao.db.QueryRow(ctx, query, q.Args()...).Scan(q.Results()...)
	if err == nil {
		data.reset()
	}

	return err
}

//// UserViews ////

const (
	sqlSelectUserViews          = `SELECT user_id, views FROM user_views`
	sqlInsertUserViews          = `INSERT INTO user_views (user_id, views) VALUES ($1, $2) ON CONFLICT (user_id) DO UPDATE SET views=user_views.views+$3 RETURNING views`
	sqlUpdateReturningUserViews = ` RETURNING views`
	sqlSelectMutatorsUserViews  = `SELECT views FROM user_views WHERE user_id=$1`
)

type UserViewsRecord struct {
	data     UserViews
	mutViews int
}

func (data UserViews) Record() *UserViewsRecord {
	return &UserViewsRecord{data: data}
}

func (model *UserViewsRecord) UserID() int {
	return model.data.UserID
}

func (model *UserViewsRecord) Views() int {
	return model.data.Views
}

func (model *UserViewsRecord) SetUserID(x int) {
	model.data.UserID = x
}

func (model *UserViewsRecord) IncViews() {
	model.mutViews++
}

func (model *UserViewsRecord) DecViews() {
	model.mutViews--
}

func (model *UserViewsRecord) AddViews(x int) {
	model.mutViews += x
}

func (*UserViewsRecord) Table() string {
	return "user_views"
}

type UserViewsDAO struct {
	db advpg.DB
}

func NewUserViewsDAO(db advpg.DB) UserViewsDAO {
	return UserViewsDAO{db: db}
}

func (model *UserViewsRecord) querySelectByUserID(inUserID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectUserViews+` WHERE user_id=$1`,
		[]any{inUserID},
		[]any{&model.data.UserID, &model.data.Views},
	)
}

func (model *UserViewsRecord) queryDeleteByUserID(inUserID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM user_views WHERE user_id=$1`,
		[]any{inUserID},
		nil,
	)
}

func (dao UserViewsDAO) SelectByUserID(ctx context.Context, inUserID int, optFuncs ...advpg.SelectOptionFunc) (UserViewsRecord, error) {
	var data UserViewsRecord
	q := data.querySelectByUserID(inUserID)
	ctx = advpgconn.QueryInfoCtx(ctx, "user_views", "UserID")
	opt := advpg.NewSelectOptions(optFuncs...)
	db := advpgconn.ReplicaByOpt(dao.db, opt, "user_views")
	row := db.QueryRow(ctx, q.SQL(), q.Args()...)
	err := row.Scan(q.Results()...)

	return data, err
}

func (dao UserViewsDAO) DeleteByUserID(ctx context.Context, inUserID int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_views", "UserID")
	q := (*UserViewsRecord)(nil).queryDeleteByUserID(inUserID)
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *UserViewsRecord) queryInsert() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlInsertUserViews,
		[]any{model.data.UserID, model.data.Views + model.mutViews, model.mutViews},
		[]any{&model.data.Views},
	)
}

func (dao UserViewsDAO) Insert(ctx context.Context, data *UserViewsRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_views", "")
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)

	return err
}

func (model *UserViewsRecord) queryUpdate() *advpg.QueryBuilder {
	if model.mutViews == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE user_views SET`)
	if model.mutViews != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" views=views+$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.mutViews)
	}
	q.AppendSQL(` WHERE user_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.UserID)

	q.AppendSQL(sqlUpdateReturningUserViews)
	q.SetResults([]any{&model.data.Views})

	return q
}

func (model *UserViewsRecord) querySelectMutators() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectMutatorsUserViews,
		[]any{model.data.UserID},
		[]any{&model.data.Views},
	)
}

func (model *UserViewsRecord) reset() {
	model.mutViews = 0
}

func (dao UserViewsDAO) Update(ctx context.Context, data *UserViewsRecord) error {
	q := advpg.Query(data.queryUpdate())
	index := ""
	query := q.SQL()
	if query == "" {
		q = data.querySelectMutators()
		query = q.SQL()
		index = "UserID"
	}
	ctx = advpgconn.QueryInfoCtx(ctx, "user_views", index)

	err := dao.db.QueryRow(ctx, query, q.Args()...).Scan(q.Results()...)
	if err == nil {
		data.reset()
	}

	return err
}

//// Seen ////

const (
	sqlSelectSeen     = `SELECT user_id, seen_at FROM seen`
	sqlInsertSeen     = `INSERT INTO seen (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING RETURNING seen_at`
	sqlFullUpdateSeen = `UPDATE seen SET seen_at=$1`
)

type SeenRecord struct {
	updateMask uint64
	data       Seen
}

func (data Seen) Record() *SeenRecord {
	return &SeenRecord{data: data}
}

func (model *SeenRecord) UserID() int {
	return model.data.UserID
}

func (model *SeenRecord) SeenAt() time.Time {
	return model.data.SeenAt
}

func (model *SeenRecord) SetUserID(x int) {
	model.data.UserID = x
}

func (model *SeenRecord) SetSeenAt(x time.Time) {
	model.data.SeenAt = x
	model.updateMask |= 1
}

func (*SeenRecord) Table() string {
	return "seen"
}

type SeenDAO struct {
	db advpg.DB
}

func NewSeenDAO(db advpg.DB) SeenDAO {
	return SeenDAO{db: db}
}

func (model *SeenRecord) querySelectByUserID(inUserID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectSeen+` WHERE user_id=$1`,
		[]any{inUserID},
		[]any{&model.data.UserID, &model.data.SeenAt},
	)
}

func (model *SeenRecord) queryDeleteByUserID(inUserID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM seen WHERE user_id=$1`,
		[]any{inUserID},
		nil,
	)
}

func (dao SeenDAO) SelectByUserID(ctx context.Context, inUserID int, optFuncs ...advpg.SelectOptionFunc) (SeenRecord, error) {
	var data SeenRecord
	q := data.querySelectByUserID(inUserID)
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "UserID")
	opt := advpg.NewSelectOptions(optFuncs...)
	db := advpgconn.ReplicaByOpt(dao.db, opt, "seen")
	row := db.QueryRow(ctx, q.SQL(), q.Args()...)
	err := row.Scan(q.Results()...)

	return data, err
}

func (dao SeenDAO) DeleteByUserID(ctx context.Context, inUserID int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "UserID")
	q := (*SeenRecord)(nil).queryDeleteByUserID(inUserID)
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *SeenRecord) queryInsert() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlInsertSeen,
		[]any{model.data.UserID},
		[]any{&model.data.SeenAt},
	)
}

func (dao SeenDAO) Insert(ctx context.Context, data *SeenRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "")
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)
	if errors.Is(err, sql.ErrNoRows) {
		return nil
	}

	return err
}

func (model *SeenRecord) queryFullUpdate() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlFullUpdateSeen+" WHERE user_id=$2",
		[]any{model.data.SeenAt, model.data.UserID},
		[]any{},
	)
}

func (dao SeenDAO) FullUpdate(ctx context.Context, data *SeenRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "")
	q := data.queryFullUpdate()
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *SeenRecord) queryUpdate() *advpg.QueryBuilder {
	if model.updateMask == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE seen SET`)
	if model.updateMask&1 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" seen_at=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.SeenAt)
	}
	q.AppendSQL(` WHERE user_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.UserID)

	return q
}

func (model *SeenRecord) reset() {
	model.updateMask = 0
}

func (dao SeenDAO) Update(ctx context.Context, data *SeenRecord) error {
	q := data.queryUpdate()
	query := q.SQL()
	if query == "" {
		return nil
	}
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "")

	ct, err := dao.db.Exec(ctx, query, q.Args()...)
	if err == nil && ct.RowsAffected() == 0 {
		err = sql.ErrNoRows
	}
	if err == nil {
		data.reset()
	}

	return err
}
