// Code generated by adv-pg. DO NOT EDIT.
//foo:bar
//foo:test

package advpgtest

import (
	"context"
	"database/sql"
	"errors"
	"time"

	advpg "github.com/my-mail-ru/go-adv-pg"
)

//// User ////

const (
	sqlSelectUser          = `SELECT id, name, type, post_count, created_at, updated_at FROM users`
	sqlInsertUser          = `INSERT INTO users (name, type) VALUES ($1, $2) RETURNING id, post_count, created_at, updated_at`
	sqlFullUpdateUser      = `UPDATE users SET name=$1, type=$2, post_count=post_count+$3`
	sqlUpdateReturningUser = ` RETURNING post_count, updated_at`
	sqlSelectMutatorsUser  = `SELECT post_count FROM users WHERE id=$1`
)

type UserTuple struct {
	updateMask   uint64
	data         User
	mutPostCount int
}

func (data User) NewTuple() *UserTuple {
	return &UserTuple{data: data}
}

func (model *UserTuple) GetID() int {
	return model.data.ID
}

func (model *UserTuple) GetName() string {
	return model.data.Name
}

func (model *UserTuple) GetType() int {
	return model.data.Type
}

func (model *UserTuple) GetPostCount() int {
	return model.data.PostCount
}

func (model *UserTuple) GetCreatedAt() time.Time {
	return model.data.CreatedAt
}

func (model *UserTuple) GetUpdatedAt() time.Time {
	return model.data.UpdatedAt
}

func (model *UserTuple) SetName(x string) {
	model.data.Name = x
	model.updateMask |= 1
}

func (model *UserTuple) SetType(x int) {
	model.data.Type = x
	model.updateMask |= 2
}

func (model *UserTuple) IncPostCount() {
	model.mutPostCount++
}

func (model *UserTuple) DecPostCount() {
	model.mutPostCount--
}

func (model *UserTuple) AddPostCount(x int) {
	model.mutPostCount += x
}

func (*UserTuple) Table() string {
	return "users"
}

type UserDAO struct {
	db advpg.DB
}

func NewUserDAO(db advpg.DB) UserDAO {
	return UserDAO{db: db}
}

func (model *UserTuple) querySelectByID(inID int) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlSelectUser + ` WHERE id=$1`,
		Args:    []any{inID},
		Results: []any{&model.data.ID, &model.data.Name, &model.data.Type, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt},
	}
}

func (model *UserTuple) queryDeleteByID(inID int) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:  `DELETE FROM users WHERE id=$1`,
		Args: []any{inID},
	}
}

func (dao UserDAO) SelectByID(ctx context.Context, inID int) (UserTuple, error) {
	var data UserTuple
	q := data.querySelectByID(inID)
	row := dao.db.QueryRow(ctx, q.GetSQL(), q.GetArgs()...)
	err := row.Scan(q.GetResults()...)

	return data, err
}

func (dao UserDAO) DeleteByID(ctx context.Context, inID int) error {
	q := (*UserTuple)(nil).queryDeleteByID(inID)
	ct, err := dao.db.Exec(ctx, q.GetSQL(), q.GetArgs()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

type SelectMultiByIDTypeKey struct {
	ID   int
	Type int
}

func (model *UserTuple) querySelectMultiByIDType(keys []SelectMultiByIDTypeKey) *advpg.QueryBuilder {
	if len(keys) == 0 {
		return &advpg.QueryBuilder{}

	}

	q := advpg.NewQueryBuilder(sqlSelectUser + ` WHERE (id, type) IN (`)

	for i, k := range keys {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.ID)
		q.AppendSQL(", $")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.Type)
		q.AppendSQL(")")
	}

	q.AppendSQL(`) ORDER BY created_at DESC`)
	q.Results = []any{&model.data.ID, &model.data.Name, &model.data.Type, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt}

	return q
}

func (model *UserTuple) queryDeleteMultiByIDType(keys []SelectMultiByIDTypeKey) *advpg.QueryBuilder {
	if len(keys) == 0 {
		return &advpg.QueryBuilder{}

	}

	q := advpg.NewQueryBuilder(`DELETE FROM users WHERE (id, type) IN (`)

	for i, k := range keys {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.ID)
		q.AppendSQL(", $")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.Type)
		q.AppendSQL(")")
	}

	q.AppendSQL(`)`)

	return q
}

func (dao UserDAO) SelectMultiByIDType(ctx context.Context, keys []SelectMultiByIDTypeKey) ([]UserTuple, error) {
	var data UserTuple
	q := data.querySelectMultiByIDType(keys)

	rows, err := dao.db.Query(ctx, q.GetSQL(), q.GetArgs()...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	ret := ([]UserTuple)(nil)

	for rows.Next() {
		if err = rows.Scan(q.GetResults()...); err != nil {
			return nil, err
		}

		ret = append(ret, data)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return ret, nil
}

func (dao UserDAO) DeleteMultiByIDType(ctx context.Context, keys []SelectMultiByIDTypeKey) error {
	q := (*UserTuple)(nil).queryDeleteMultiByIDType(keys)
	_, err := dao.db.Exec(ctx, q.GetSQL(), q.GetArgs()...)
	return err
}

func (model *UserTuple) querySelectByName(inName string) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlSelectUser + ` WHERE name=$1`,
		Args:    []any{inName},
		Results: []any{&model.data.ID, &model.data.Name, &model.data.Type, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt},
	}
}

func (model *UserTuple) queryDeleteByName(inName string) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:  `DELETE FROM users WHERE name=$1`,
		Args: []any{inName},
	}
}

func (dao UserDAO) SelectByName(ctx context.Context, inName string) ([]UserTuple, error) {
	var data UserTuple
	q := data.querySelectByName(inName)

	rows, err := dao.db.Query(ctx, q.GetSQL(), q.GetArgs()...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	ret := ([]UserTuple)(nil)

	for rows.Next() {
		if err = rows.Scan(q.GetResults()...); err != nil {
			return nil, err
		}

		ret = append(ret, data)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return ret, nil
}

func (dao UserDAO) DeleteByName(ctx context.Context, inName string) error {
	q := (*UserTuple)(nil).queryDeleteByName(inName)
	_, err := dao.db.Exec(ctx, q.GetSQL(), q.GetArgs()...)
	return err
}

func (model *UserTuple) queryInsert() *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlInsertUser,
		Args:    []any{model.data.Name, model.data.Type},
		Results: []any{&model.data.ID, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt},
	}
}

func (dao UserDAO) Insert(ctx context.Context, data *UserTuple) error {
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.GetSQL(), q.GetArgs()...).Scan(q.GetResults()...)

	return err
}

func (model *UserTuple) queryFullUpdate() *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlFullUpdateUser + " WHERE id=$4" + sqlUpdateReturningUser,
		Args:    []any{model.data.Name, model.data.Type, model.mutPostCount, model.data.ID},
		Results: []any{&model.data.PostCount, &model.data.UpdatedAt},
	}
}

func (dao UserDAO) FullUpdate(ctx context.Context, data *UserTuple) error {
	q := data.queryFullUpdate()
	return dao.db.QueryRow(ctx, q.GetSQL(), q.GetArgs()...).Scan(q.GetResults()...)
}

func (model *UserTuple) queryUpdate() *advpg.QueryBuilder {
	if model.updateMask == 0 && model.mutPostCount == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE users SET`)
	if model.updateMask&1 != 0 {
		if len(q.Args) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" name=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Name)
	}
	if model.updateMask&2 != 0 {
		if len(q.Args) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" type=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Type)
	}
	if model.mutPostCount != 0 {
		if len(q.Args) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" post_count=post_count+$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.mutPostCount)
	}
	q.AppendSQL(` WHERE id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.ID)

	q.AppendSQL(sqlUpdateReturningUser)
	q.Results = []any{&model.data.PostCount, &model.data.UpdatedAt}

	return q
}

func (model *UserTuple) querySelectMutators() *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlSelectMutatorsUser,
		Args:    []any{model.data.ID},
		Results: []any{&model.data.PostCount},
	}
}

func (model *UserTuple) reset() {
	model.updateMask = 0
	model.mutPostCount = 0
}

func (dao UserDAO) Update(ctx context.Context, data *UserTuple) error {
	q := advpg.Query(data.queryUpdate())
	query := q.GetSQL()
	if query == "" {
		q = data.querySelectMutators()
		query = q.GetSQL()
	}

	err := dao.db.QueryRow(ctx, query, q.GetArgs()...).Scan(q.GetResults()...)
	if err == nil {
		data.reset()
	}

	return err
}

//// ExtLink ////

const (
	sqlSelectExtLink          = `SELECT user_id, ext_id, EXTRACT(EPOCH FROM created_at::TIMESTAMP WITH TIME ZONE)::BIGINT AS created_at, status, link_count FROM ext_links`
	sqlInsertExtLink          = `INSERT INTO ext_links (user_id, ext_id, created_at, status) VALUES ($1, $2, TIMESTAMP WITH TIME ZONE 'epoch' + INTERVAL '1 sec' * $3, $4) ON CONFLICT (user_id, ext_id) DO UPDATE SET status=EXCLUDED.status, link_count=ext_links.link_count+$5 RETURNING link_count`
	sqlFullUpdateExtLink      = `UPDATE ext_links SET status=$1, link_count=link_count+$2`
	sqlUpdateReturningExtLink = ` RETURNING link_count`
	sqlSelectMutatorsExtLink  = `SELECT link_count FROM ext_links WHERE user_id=$1 AND ext_id=$2`
)

type ExtLinkTuple struct {
	updateMask   uint64
	data         ExtLink
	mutLinkCount int
}

func (data ExtLink) NewTuple() *ExtLinkTuple {
	return &ExtLinkTuple{data: data}
}

func (model *ExtLinkTuple) GetUserID() int {
	return model.data.UserID
}

func (model *ExtLinkTuple) GetExternalID() int {
	return model.data.ExternalID
}

func (model *ExtLinkTuple) GetCreatedAt() MyTime {
	return model.data.CreatedAt
}

func (model *ExtLinkTuple) GetStatus() int {
	return model.data.Status
}

func (model *ExtLinkTuple) GetLinkCount() int {
	return model.data.LinkCount
}

func (model *ExtLinkTuple) SetUserID(x int) {
	model.data.UserID = x
}

func (model *ExtLinkTuple) SetExternalID(x int) {
	model.data.ExternalID = x
}

func (model *ExtLinkTuple) SetCreatedAt(x MyTime) {
	model.data.CreatedAt = x
}

func (model *ExtLinkTuple) SetStatus(x int) {
	model.data.Status = x
	model.updateMask |= 1
}

func (model *ExtLinkTuple) IncLinkCount() {
	model.mutLinkCount++
}

func (model *ExtLinkTuple) DecLinkCount() {
	model.mutLinkCount--
}

func (model *ExtLinkTuple) AddLinkCount(x int) {
	model.mutLinkCount += x
}

func (*ExtLinkTuple) Table() string {
	return "ext_links"
}

type ExtLinkDAO struct {
	db advpg.DB
}

func NewExtLinkDAO(db advpg.DB) ExtLinkDAO {
	return ExtLinkDAO{db: db}
}

func (model *ExtLinkTuple) querySelectByPrimaryKey(inUserID int, inExternalID int) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlSelectExtLink + ` WHERE user_id=$1 AND ext_id=$2`,
		Args:    []any{inUserID, inExternalID},
		Results: []any{&model.data.UserID, &model.data.ExternalID, &model.data.CreatedAt, &model.data.Status, &model.data.LinkCount},
	}
}

func (model *ExtLinkTuple) queryDeleteByPrimaryKey(inUserID int, inExternalID int) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:  `DELETE FROM ext_links WHERE user_id=$1 AND ext_id=$2`,
		Args: []any{inUserID, inExternalID},
	}
}

func (dao ExtLinkDAO) SelectByPrimaryKey(ctx context.Context, inUserID int, inExternalID int) (ExtLinkTuple, error) {
	var data ExtLinkTuple
	q := data.querySelectByPrimaryKey(inUserID, inExternalID)
	row := dao.db.QueryRow(ctx, q.GetSQL(), q.GetArgs()...)
	err := row.Scan(q.GetResults()...)

	return data, err
}

func (dao ExtLinkDAO) DeleteByPrimaryKey(ctx context.Context, inUserID int, inExternalID int) error {
	q := (*ExtLinkTuple)(nil).queryDeleteByPrimaryKey(inUserID, inExternalID)
	ct, err := dao.db.Exec(ctx, q.GetSQL(), q.GetArgs()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *ExtLinkTuple) querySelectMultiByStatus(inStatuses []int) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlSelectExtLink + ` WHERE status=IN($1)`,
		Args:    []any{inStatuses},
		Results: []any{&model.data.UserID, &model.data.ExternalID, &model.data.CreatedAt, &model.data.Status, &model.data.LinkCount},
	}
}

func (model *ExtLinkTuple) queryDeleteMultiByStatus(inStatuses []int) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:  `DELETE FROM ext_links WHERE status=IN($1)`,
		Args: []any{inStatuses},
	}
}

func (dao ExtLinkDAO) SelectMultiByStatus(ctx context.Context, inStatuses []int) ([]ExtLinkTuple, error) {
	var data ExtLinkTuple
	q := data.querySelectMultiByStatus(inStatuses)

	rows, err := dao.db.Query(ctx, q.GetSQL(), q.GetArgs()...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	ret := ([]ExtLinkTuple)(nil)

	for rows.Next() {
		if err = rows.Scan(q.GetResults()...); err != nil {
			return nil, err
		}

		ret = append(ret, data)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return ret, nil
}

func (dao ExtLinkDAO) DeleteMultiByStatus(ctx context.Context, inStatuses []int) error {
	q := (*ExtLinkTuple)(nil).queryDeleteMultiByStatus(inStatuses)
	_, err := dao.db.Exec(ctx, q.GetSQL(), q.GetArgs()...)
	return err
}

func (model *ExtLinkTuple) queryInsert() *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlInsertExtLink,
		Args:    []any{model.data.UserID, model.data.ExternalID, model.data.CreatedAt, model.data.Status, model.mutLinkCount},
		Results: []any{&model.data.LinkCount},
	}
}

func (dao ExtLinkDAO) Insert(ctx context.Context, data *ExtLinkTuple) error {
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.GetSQL(), q.GetArgs()...).Scan(q.GetResults()...)

	return err
}

func (model *ExtLinkTuple) queryFullUpdate() *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlFullUpdateExtLink + " WHERE user_id=$3 AND ext_id=$4" + sqlUpdateReturningExtLink,
		Args:    []any{model.data.Status, model.mutLinkCount, model.data.UserID, model.data.ExternalID},
		Results: []any{&model.data.LinkCount},
	}
}

func (dao ExtLinkDAO) FullUpdate(ctx context.Context, data *ExtLinkTuple) error {
	q := data.queryFullUpdate()
	return dao.db.QueryRow(ctx, q.GetSQL(), q.GetArgs()...).Scan(q.GetResults()...)
}

func (model *ExtLinkTuple) queryUpdate() *advpg.QueryBuilder {
	if model.updateMask == 0 && model.mutLinkCount == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE ext_links SET`)
	if model.updateMask&1 != 0 {
		if len(q.Args) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" status=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Status)
	}
	if model.mutLinkCount != 0 {
		if len(q.Args) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" link_count=link_count+$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.mutLinkCount)
	}
	q.AppendSQL(` WHERE user_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.UserID)
	q.AppendSQL(` AND ext_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.ExternalID)

	q.AppendSQL(sqlUpdateReturningExtLink)
	q.Results = []any{&model.data.LinkCount}

	return q
}

func (model *ExtLinkTuple) querySelectMutators() *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlSelectMutatorsExtLink,
		Args:    []any{model.data.UserID, model.data.ExternalID},
		Results: []any{&model.data.LinkCount},
	}
}

func (model *ExtLinkTuple) reset() {
	model.updateMask = 0
	model.mutLinkCount = 0
}

func (dao ExtLinkDAO) Update(ctx context.Context, data *ExtLinkTuple) error {
	q := advpg.Query(data.queryUpdate())
	query := q.GetSQL()
	if query == "" {
		q = data.querySelectMutators()
		query = q.GetSQL()
	}

	err := dao.db.QueryRow(ctx, query, q.GetArgs()...).Scan(q.GetResults()...)
	if err == nil {
		data.reset()
	}

	return err
}

//// UserViews ////

const (
	sqlSelectUserViews          = `SELECT user_id, views FROM user_views`
	sqlInsertUserViews          = `INSERT INTO user_views (user_id, views) VALUES ($1, $2) ON CONFLICT (user_id) DO UPDATE SET views=user_views.views+$3 RETURNING views`
	sqlUpdateReturningUserViews = ` RETURNING views`
	sqlSelectMutatorsUserViews  = `SELECT views FROM user_views WHERE user_id=$1`
)

type UserViewsTuple struct {
	data     UserViews
	mutViews int
}

func (data UserViews) NewTuple() *UserViewsTuple {
	return &UserViewsTuple{data: data}
}

func (model *UserViewsTuple) GetUserID() int {
	return model.data.UserID
}

func (model *UserViewsTuple) GetViews() int {
	return model.data.Views
}

func (model *UserViewsTuple) SetUserID(x int) {
	model.data.UserID = x
}

func (model *UserViewsTuple) IncViews() {
	model.mutViews++
}

func (model *UserViewsTuple) DecViews() {
	model.mutViews--
}

func (model *UserViewsTuple) AddViews(x int) {
	model.mutViews += x
}

func (*UserViewsTuple) Table() string {
	return "user_views"
}

type UserViewsDAO struct {
	db advpg.DB
}

func NewUserViewsDAO(db advpg.DB) UserViewsDAO {
	return UserViewsDAO{db: db}
}

func (model *UserViewsTuple) querySelectByUserID(inUserID int) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlSelectUserViews + ` WHERE user_id=$1`,
		Args:    []any{inUserID},
		Results: []any{&model.data.UserID, &model.data.Views},
	}
}

func (model *UserViewsTuple) queryDeleteByUserID(inUserID int) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:  `DELETE FROM user_views WHERE user_id=$1`,
		Args: []any{inUserID},
	}
}

func (dao UserViewsDAO) SelectByUserID(ctx context.Context, inUserID int) (UserViewsTuple, error) {
	var data UserViewsTuple
	q := data.querySelectByUserID(inUserID)
	row := dao.db.QueryRow(ctx, q.GetSQL(), q.GetArgs()...)
	err := row.Scan(q.GetResults()...)

	return data, err
}

func (dao UserViewsDAO) DeleteByUserID(ctx context.Context, inUserID int) error {
	q := (*UserViewsTuple)(nil).queryDeleteByUserID(inUserID)
	ct, err := dao.db.Exec(ctx, q.GetSQL(), q.GetArgs()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *UserViewsTuple) queryInsert() *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlInsertUserViews,
		Args:    []any{model.data.UserID, model.data.Views + model.mutViews, model.mutViews},
		Results: []any{&model.data.Views},
	}
}

func (dao UserViewsDAO) Insert(ctx context.Context, data *UserViewsTuple) error {
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.GetSQL(), q.GetArgs()...).Scan(q.GetResults()...)

	return err
}

func (model *UserViewsTuple) queryUpdate() *advpg.QueryBuilder {
	if model.mutViews == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE user_views SET`)
	if model.mutViews != 0 {
		if len(q.Args) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" views=views+$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.mutViews)
	}
	q.AppendSQL(` WHERE user_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.UserID)

	q.AppendSQL(sqlUpdateReturningUserViews)
	q.Results = []any{&model.data.Views}

	return q
}

func (model *UserViewsTuple) querySelectMutators() *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlSelectMutatorsUserViews,
		Args:    []any{model.data.UserID},
		Results: []any{&model.data.Views},
	}
}

func (model *UserViewsTuple) reset() {
	model.mutViews = 0
}

func (dao UserViewsDAO) Update(ctx context.Context, data *UserViewsTuple) error {
	q := advpg.Query(data.queryUpdate())
	query := q.GetSQL()
	if query == "" {
		q = data.querySelectMutators()
		query = q.GetSQL()
	}

	err := dao.db.QueryRow(ctx, query, q.GetArgs()...).Scan(q.GetResults()...)
	if err == nil {
		data.reset()
	}

	return err
}

//// Seen ////

const (
	sqlSelectSeen     = `SELECT user_id, seen_at FROM seen`
	sqlInsertSeen     = `INSERT INTO seen (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING RETURNING seen_at`
	sqlFullUpdateSeen = `UPDATE seen SET seen_at=$1`
)

type SeenTuple struct {
	updateMask uint64
	data       Seen
}

func (data Seen) NewTuple() *SeenTuple {
	return &SeenTuple{data: data}
}

func (model *SeenTuple) GetUserID() int {
	return model.data.UserID
}

func (model *SeenTuple) GetSeenAt() time.Time {
	return model.data.SeenAt
}

func (model *SeenTuple) SetUserID(x int) {
	model.data.UserID = x
}

func (model *SeenTuple) SetSeenAt(x time.Time) {
	model.data.SeenAt = x
	model.updateMask |= 1
}

func (*SeenTuple) Table() string {
	return "seen"
}

type SeenDAO struct {
	db advpg.DB
}

func NewSeenDAO(db advpg.DB) SeenDAO {
	return SeenDAO{db: db}
}

func (model *SeenTuple) querySelectByUserID(inUserID int) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlSelectSeen + ` WHERE user_id=$1`,
		Args:    []any{inUserID},
		Results: []any{&model.data.UserID, &model.data.SeenAt},
	}
}

func (model *SeenTuple) queryDeleteByUserID(inUserID int) *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:  `DELETE FROM seen WHERE user_id=$1`,
		Args: []any{inUserID},
	}
}

func (dao SeenDAO) SelectByUserID(ctx context.Context, inUserID int) (SeenTuple, error) {
	var data SeenTuple
	q := data.querySelectByUserID(inUserID)
	row := dao.db.QueryRow(ctx, q.GetSQL(), q.GetArgs()...)
	err := row.Scan(q.GetResults()...)

	return data, err
}

func (dao SeenDAO) DeleteByUserID(ctx context.Context, inUserID int) error {
	q := (*SeenTuple)(nil).queryDeleteByUserID(inUserID)
	ct, err := dao.db.Exec(ctx, q.GetSQL(), q.GetArgs()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *SeenTuple) queryInsert() *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlInsertSeen,
		Args:    []any{model.data.UserID},
		Results: []any{&model.data.SeenAt},
	}
}

func (dao SeenDAO) Insert(ctx context.Context, data *SeenTuple) error {
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.GetSQL(), q.GetArgs()...).Scan(q.GetResults()...)
	if errors.Is(err, sql.ErrNoRows) {
		return nil
	}

	return err
}

func (model *SeenTuple) queryFullUpdate() *advpg.SimpleQuery {
	return &advpg.SimpleQuery{
		SQL:     sqlFullUpdateSeen + " WHERE user_id=$2",
		Args:    []any{model.data.SeenAt, model.data.UserID},
		Results: []any{},
	}
}

func (dao SeenDAO) FullUpdate(ctx context.Context, data *SeenTuple) error {
	q := data.queryFullUpdate()
	ct, err := dao.db.Exec(ctx, q.GetSQL(), q.GetArgs()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *SeenTuple) queryUpdate() *advpg.QueryBuilder {
	if model.updateMask == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE seen SET`)
	if model.updateMask&1 != 0 {
		if len(q.Args) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" seen_at=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.SeenAt)
	}
	q.AppendSQL(` WHERE user_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.UserID)

	return q
}

func (model *SeenTuple) reset() {
	model.updateMask = 0
}

func (dao SeenDAO) Update(ctx context.Context, data *SeenTuple) error {
	q := data.queryUpdate()
	query := q.GetSQL()
	if query == "" {
		return nil
	}

	ct, err := dao.db.Exec(ctx, query, q.GetArgs()...)
	if err == nil && ct.RowsAffected() == 0 {
		err = sql.ErrNoRows
	}
	if err == nil {
		data.reset()
	}

	return err
}
