// Code generated by adv-pg. DO NOT EDIT.
//foo:bar
//foo:test

package advpgtest

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	advpg "github.com/my-mail-ru/go-adv-pg"
	advpgconn "github.com/my-mail-ru/go-adv-pg/conn"
)

//// ExtLink ////

const (
	sqlSelectExtLink          = `SELECT user_id, ext_id, EXTRACT(EPOCH FROM created_at::TIMESTAMP WITH TIME ZONE)::BIGINT AS created_at, status, link_count, EXTRACT(EPOCH FROM modified_at::TIMESTAMP WITH TIME ZONE)::BIGINT AS modified_at, EXTRACT(EPOCH FROM refreshed_at::TIMESTAMP WITH TIME ZONE)::BIGINT AS refreshed_at FROM ext_links`
	sqlInsertHeadExtLink      = `INSERT INTO ext_links (user_id, ext_id, created_at, status) VALUES `
	sqlInsertTailExtLink      = ` ON CONFLICT (user_id, ext_id) DO UPDATE SET status=EXCLUDED.status, modified_at=EXCLUDED.modified_at, link_count=ext_links.link_count+$5 RETURNING link_count, EXTRACT(EPOCH FROM modified_at::TIMESTAMP WITH TIME ZONE)::BIGINT AS modified_at, EXTRACT(EPOCH FROM refreshed_at::TIMESTAMP WITH TIME ZONE)::BIGINT AS refreshed_at`
	sqlInsertExtLink          = sqlInsertHeadExtLink + `($1, $2, TIMESTAMP WITH TIME ZONE 'epoch' + INTERVAL '1 sec' * $3, $4)` + sqlInsertTailExtLink
	sqlFullUpdateExtLink      = `UPDATE ext_links SET status=$1, modified_at=TIMESTAMP WITH TIME ZONE 'epoch' + INTERVAL '1 sec' * $2, link_count=link_count+$3`
	sqlUpdateReturningExtLink = ` RETURNING link_count, EXTRACT(EPOCH FROM refreshed_at::TIMESTAMP WITH TIME ZONE)::BIGINT AS refreshed_at`
	sqlUpdateMultiHeadExtLink = `UPDATE ext_links SET status=(t::ext_links).status, modified_at=(t::ext_links).modified_at, link_count=ext_links.link_count+(t::ext_links).link_count FROM (VALUES `
	sqlUpdateMultiTailExtLink = `) t WHERE ext_links.user_id=(t::ext_links).user_id AND ext_links.ext_id=(t::ext_links).ext_id RETURNING ext_links.link_count, EXTRACT(EPOCH FROM ext_links.refreshed_at::TIMESTAMP WITH TIME ZONE)::BIGINT AS refreshed_at`
	sqlSelectMutatorsExtLink  = `SELECT link_count FROM ext_links WHERE user_id=$1 AND ext_id=$2`

	sqlDeleteExtLink          = `DELETE FROM ext_links WHERE user_id=$1 AND ext_id=$2`
	sqlDeleteMultiHeadExtLink = `DELETE FROM ext_links WHERE (user_id, ext_id) IN (`
)

type ExtLinkRecord struct {
	updateMask   uint64
	data         ExtLink
	mutLinkCount int
}

func (data ExtLink) Record() *ExtLinkRecord {
	return &ExtLinkRecord{data: data}
}

func (model *ExtLinkRecord) UserID() int {
	return model.data.UserID
}

func (model *ExtLinkRecord) ExternalID() int {
	return model.data.ExternalID
}

func (model *ExtLinkRecord) CreatedAt() MyTime {
	return model.data.CreatedAt
}

func (model *ExtLinkRecord) Status() int {
	return model.data.Status
}

func (model *ExtLinkRecord) LinkCount() int {
	return model.data.LinkCount
}

func (model *ExtLinkRecord) ModifiedAt() MyTime {
	return model.data.ModifiedAt
}

func (model *ExtLinkRecord) RefreshedAt() MyTime {
	return model.data.RefreshedAt
}

func (model *ExtLinkRecord) SetUserID(x int) {
	model.data.UserID = x
}

func (model *ExtLinkRecord) SetExternalID(x int) {
	model.data.ExternalID = x
}

func (model *ExtLinkRecord) SetCreatedAt(x MyTime) {
	model.data.CreatedAt = x
}

func (model *ExtLinkRecord) SetStatus(x int) {
	model.data.Status = x
	model.updateMask |= 1
}

func (model *ExtLinkRecord) SetModifiedAt(x MyTime) {
	model.data.ModifiedAt = x
	model.updateMask |= 2
}

func (model *ExtLinkRecord) IncLinkCount() {
	model.mutLinkCount++
}

func (model *ExtLinkRecord) DecLinkCount() {
	model.mutLinkCount--
}

func (model *ExtLinkRecord) AddLinkCount(x int) {
	model.mutLinkCount += x
}

func (*ExtLinkRecord) Table() string {
	return "ext_links"
}

type ExtLinkDAO struct {
	db advpg.DB
}

func NewExtLinkDAO(db advpg.DB) ExtLinkDAO {
	return ExtLinkDAO{db: db}
}

func (model *ExtLinkRecord) querySelectByPrimaryKey(inUserID int, inExternalID int, limit, offset uint) *advpg.SimpleQuery {
	sql := sqlSelectExtLink + ` WHERE user_id=$1 AND ext_id=$2`
	if limit > 0 {
		sql += " LIMIT " + strconv.FormatUint(uint64(limit), 10)
	}
	if offset > 0 {
		sql += " OFFSET " + strconv.FormatUint(uint64(offset), 10)
	}
	return advpg.NewSimpleQuery(
		sql,
		[]any{inUserID, inExternalID},
		[]any{&model.data.UserID, &model.data.ExternalID, &model.data.CreatedAt, &model.data.Status, &model.data.LinkCount, &model.data.ModifiedAt, &model.data.RefreshedAt},
	)
}

func (model *ExtLinkRecord) queryDeleteByPrimaryKey(inUserID int, inExternalID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM ext_links WHERE user_id=$1 AND ext_id=$2`,
		[]any{inUserID, inExternalID},
		nil,
	)
}

func (dao ExtLinkDAO) SelectByPrimaryKey(ctx context.Context, inUserID int, inExternalID int, optFuncs ...advpg.SelectOptionFunc) (ExtLinkRecord, error) {
	var data ExtLinkRecord
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "PrimaryKey")
	opt := advpg.NewSelectOptions(optFuncs...)
	limit := opt.Limit()
	q := data.querySelectByPrimaryKey(inUserID, inExternalID, limit, opt.Offset())
	db := advpgconn.ReplicaByOpt(dao.db, opt, "ext_links")
	row := db.QueryRow(ctx, q.SQL(), q.Args()...)
	err := row.Scan(q.Results()...)

	return data, err
}

func (dao ExtLinkDAO) DeleteByPrimaryKey(ctx context.Context, inUserID int, inExternalID int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "PrimaryKey")
	q := (*ExtLinkRecord)(nil).queryDeleteByPrimaryKey(inUserID, inExternalID)
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *ExtLinkRecord) querySelectMultiByStatus(inStatuses []int, limit, offset uint) *advpg.SimpleQuery {
	sql := sqlSelectExtLink + ` WHERE status=IN($1)`
	if limit > 0 {
		sql += " LIMIT " + strconv.FormatUint(uint64(limit), 10)
	}
	if offset > 0 {
		sql += " OFFSET " + strconv.FormatUint(uint64(offset), 10)
	}
	return advpg.NewSimpleQuery(
		sql,
		[]any{inStatuses},
		[]any{&model.data.UserID, &model.data.ExternalID, &model.data.CreatedAt, &model.data.Status, &model.data.LinkCount, &model.data.ModifiedAt, &model.data.RefreshedAt},
	)
}

func (model *ExtLinkRecord) queryDeleteMultiByStatus(inStatuses []int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM ext_links WHERE status=IN($1)`,
		[]any{inStatuses},
		nil,
	)
}

func (dao ExtLinkDAO) SelectMultiByStatus(ctx context.Context, inStatuses []int, optFuncs ...advpg.SelectOptionFunc) ([]ExtLinkRecord, error) {
	var data ExtLinkRecord
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "Status")
	opt := advpg.NewSelectOptions(optFuncs...)
	limit := opt.Limit()
	q := data.querySelectMultiByStatus(inStatuses, limit, opt.Offset())
	db := advpgconn.ReplicaByOpt(dao.db, opt, "ext_links")

	rows, err := db.Query(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	ret := ([]ExtLinkRecord)(nil)

	for rows.Next() {
		if err = rows.Scan(q.Results()...); err != nil {
			return nil, err
		}

		ret = append(ret, data)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return ret, nil
}

func (dao ExtLinkDAO) DeleteMultiByStatus(ctx context.Context, inStatuses []int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "Status")
	q := (*ExtLinkRecord)(nil).queryDeleteMultiByStatus(inStatuses)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

func (model *ExtLinkRecord) queryInsert() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlInsertExtLink,
		[]any{model.data.UserID, model.data.ExternalID, model.data.CreatedAt, model.data.Status, model.mutLinkCount},
		[]any{&model.data.LinkCount, &model.data.ModifiedAt, &model.data.RefreshedAt},
	)
}

func (dao ExtLinkDAO) Insert(ctx context.Context, data *ExtLinkRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "")
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)

	if err == nil {
		data.reset()
	}

	return err
}

func queryUpdateMultiExtLink(models []ExtLinkRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilderCap(sqlUpdateMultiHeadExtLink, 5*len(models), 2*len(models))

	for i, model := range models {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}

		q.AppendPlaceholder()
		q.AppendArgs(model.data.UserID)
		q.AppendSQL(",")
		q.AppendPlaceholder()
		q.AppendArgs(model.data.ExternalID)
		q.AppendSQL(",")
		q.AppendSQL("NULL")
		q.AppendSQL(",")
		q.AppendPlaceholder()
		q.AppendArgs(model.data.Status)
		q.AppendSQL(",")
		q.AppendPlaceholder()
		q.AppendArgs(model.mutLinkCount)
		q.AppendSQL(",")
		q.AppendSQL(strings.ReplaceAll("TIMESTAMP WITH TIME ZONE 'epoch' + INTERVAL '1 sec' * %s", "%s", q.Placeholder()))
		q.AppendArgs(model.data.ModifiedAt)
		q.AppendSQL(",")
		q.AppendSQL("NULL")
		q.AppendSQL(")")

		q.AppendResults(&models[i].data.LinkCount, &models[i].data.RefreshedAt)
	}

	q.AppendSQL(sqlUpdateMultiTailExtLink)

	return q
}

func (dao ExtLinkDAO) UpdateMulti(ctx context.Context, records []ExtLinkRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "")
	q := queryUpdateMultiExtLink(records)
	rows, err := dao.db.Query(ctx, q.SQL(), q.Args()...)
	defer rows.Close()

	if err == nil {
		results := q.Results()
		from := 0
		to := 2

		for rows.Next() {
			if err = rows.Scan(results[from:to]...); err != nil {
				break
			}

			from = to
			to += 2
		}

		if err == nil {
			err = rows.Err()
		}

		if from < len(results) {
			err = fmt.Errorf("ExtLinkDAO.UpdateMulti: got %d records, but %d was expected", from/2, len(results)/2)
		}
	}

	if err == nil {
		for i := range records {
			records[i].reset()
		}
	}

	return err
}

func (model *ExtLinkRecord) queryFullUpdate() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlFullUpdateExtLink+" WHERE user_id=$4 AND ext_id=$5"+sqlUpdateReturningExtLink,
		[]any{model.data.Status, model.data.ModifiedAt, model.mutLinkCount, model.data.UserID, model.data.ExternalID},
		[]any{&model.data.LinkCount, &model.data.RefreshedAt},
	)
}

func (dao ExtLinkDAO) FullUpdate(ctx context.Context, data *ExtLinkRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "")
	q := data.queryFullUpdate()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)

	if err == nil {
		data.reset()
	}

	return err
}

func (model *ExtLinkRecord) queryUpdate() *advpg.QueryBuilder {
	if model.updateMask == 0 && model.mutLinkCount == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE ext_links SET`)
	if model.updateMask&1 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" status=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Status)
	}
	if model.updateMask&2 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" modified_at=")
		q.AppendSQL(strings.ReplaceAll("TIMESTAMP WITH TIME ZONE 'epoch' + INTERVAL '1 sec' * %s", "%s", q.Placeholder()))
		q.AppendArgs(model.data.ModifiedAt)
	}
	if model.mutLinkCount != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" link_count=link_count+$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.mutLinkCount)
	}
	q.AppendSQL(` WHERE user_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.UserID)
	q.AppendSQL(` AND ext_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.ExternalID)

	q.AppendSQL(sqlUpdateReturningExtLink)
	q.SetResults([]any{&model.data.LinkCount, &model.data.RefreshedAt})

	return q
}

func (model *ExtLinkRecord) querySelectMutators() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectMutatorsExtLink,
		[]any{model.data.UserID, model.data.ExternalID},
		[]any{&model.data.LinkCount},
	)
}

func (model *ExtLinkRecord) reset() {
	model.updateMask = 0
	model.mutLinkCount = 0
}
func (dao ExtLinkDAO) Update(ctx context.Context, data *ExtLinkRecord) error {
	q := advpg.Query(data.queryUpdate())
	index := ""
	query := q.SQL()
	if query == "" {
		q = data.querySelectMutators()
		query = q.SQL()
		index = "PrimaryKey"
	}
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", index)

	err := dao.db.QueryRow(ctx, query, q.Args()...).Scan(q.Results()...)
	if err == nil {
		data.reset()
	}

	return err
}
func (model *ExtLinkRecord) queryDelete() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlDeleteExtLink,
		[]any{model.data.UserID, model.data.ExternalID},
		nil,
	)
}

func (dao ExtLinkDAO) Delete(ctx context.Context, data *ExtLinkRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "")
	q := data.queryDelete()
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func queryDeleteMultiExtLink(models []ExtLinkRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(sqlDeleteMultiHeadExtLink)

	for i, model := range models {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.UserID)
		q.AppendSQL(", $")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.ExternalID)
		q.AppendSQL(")")
	}

	q.AppendSQL(")")
	return q
}

func (dao ExtLinkDAO) DeleteMulti(ctx context.Context, records []ExtLinkRecord) error {
	if len(records) == 0 {
		return nil
	}

	ctx = advpgconn.QueryInfoCtx(ctx, "ext_links", "")
	q := queryDeleteMultiExtLink(records)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

//// Seen ////

const (
	sqlSelectSeen          = `SELECT user_id, seen_at FROM seen`
	sqlInsertHeadSeen      = `INSERT INTO seen (user_id) VALUES `
	sqlInsertTailSeen      = ` ON CONFLICT (user_id) DO NOTHING RETURNING seen_at`
	sqlInsertSeen          = sqlInsertHeadSeen + `($1)` + sqlInsertTailSeen
	sqlFullUpdateSeen      = `UPDATE seen SET seen_at=$1`
	sqlUpdateMultiHeadSeen = `UPDATE seen SET seen_at=(t::seen).seen_at FROM (VALUES `
	sqlUpdateMultiTailSeen = `) t WHERE seen.user_id=(t::seen).user_id`
	sqlDeleteSeen          = `DELETE FROM seen WHERE user_id=$1`
	sqlDeleteMultiHeadSeen = `DELETE FROM seen WHERE user_id IN (`
)

type Seen struct {
	UserID int       `db:"user_id"`
	SeenAt time.Time `db:"seen_at"`
}

type SeenRecord struct {
	updateMask uint64
	data       Seen
}

func (data Seen) Record() *SeenRecord {
	return &SeenRecord{data: data}
}

func (model *SeenRecord) UserID() int {
	return model.data.UserID
}

func (model *SeenRecord) SeenAt() time.Time {
	return model.data.SeenAt
}

func (model *SeenRecord) SetUserID(x int) {
	model.data.UserID = x
}

func (model *SeenRecord) SetSeenAt(x time.Time) {
	model.data.SeenAt = x
	model.updateMask |= 1
}

func (*SeenRecord) Table() string {
	return "seen"
}

type SeenDAO struct {
	db advpg.DB
}

func NewSeenDAO(db advpg.DB) SeenDAO {
	return SeenDAO{db: db}
}

func (model *SeenRecord) querySelectByUserID(inUserID int, limit, offset uint) *advpg.SimpleQuery {
	sql := sqlSelectSeen + ` WHERE user_id=$1`
	if limit > 0 {
		sql += " LIMIT " + strconv.FormatUint(uint64(limit), 10)
	}
	if offset > 0 {
		sql += " OFFSET " + strconv.FormatUint(uint64(offset), 10)
	}
	return advpg.NewSimpleQuery(
		sql,
		[]any{inUserID},
		[]any{&model.data.UserID, &model.data.SeenAt},
	)
}

func (model *SeenRecord) queryDeleteByUserID(inUserID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM seen WHERE user_id=$1`,
		[]any{inUserID},
		nil,
	)
}

func (dao SeenDAO) SelectByUserID(ctx context.Context, inUserID int, optFuncs ...advpg.SelectOptionFunc) (SeenRecord, error) {
	var data SeenRecord
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "UserID")
	opt := advpg.NewSelectOptions(optFuncs...)
	limit := opt.Limit()
	q := data.querySelectByUserID(inUserID, limit, opt.Offset())
	db := advpgconn.ReplicaByOpt(dao.db, opt, "seen")
	row := db.QueryRow(ctx, q.SQL(), q.Args()...)
	err := row.Scan(q.Results()...)

	return data, err
}

func (dao SeenDAO) DeleteByUserID(ctx context.Context, inUserID int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "UserID")
	q := (*SeenRecord)(nil).queryDeleteByUserID(inUserID)
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *SeenRecord) queryInsert() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlInsertSeen,
		[]any{model.data.UserID},
		[]any{&model.data.SeenAt},
	)
}

func (dao SeenDAO) Insert(ctx context.Context, data *SeenRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "")
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)
	if errors.Is(err, sql.ErrNoRows) {
		return nil
	}

	if err == nil {
		data.reset()
	}

	return err
}

func queryInsertMultiSeen(models []SeenRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilderCap(sqlInsertHeadSeen, 1*len(models), 1*len(models))

	for i, model := range models {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}

		q.AppendPlaceholder()
		q.AppendArgs(model.data.UserID)
		q.AppendSQL(")")

		q.AppendResults(&models[i].data.SeenAt)
	}

	q.AppendSQL(sqlInsertTailSeen)

	return q
}

func (dao SeenDAO) InsertMulti(ctx context.Context, records []SeenRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "")
	q := queryInsertMultiSeen(records)
	rows, err := dao.db.Query(ctx, q.SQL(), q.Args()...)
	defer rows.Close()

	if err == nil {
		results := q.Results()
		from := 0
		to := 1

		for rows.Next() {
			if err = rows.Scan(results[from:to]...); err != nil {
				break
			}

			from = to
			to += 1
		}

		if err == nil {
			err = rows.Err()
		}

	}

	if err == nil {
		for i := range records {
			records[i].reset()
		}
	}

	return err
}

func queryUpdateMultiSeen(models []SeenRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilderCap(sqlUpdateMultiHeadSeen, 2*len(models), 0)

	for i, model := range models {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}

		q.AppendPlaceholder()
		q.AppendArgs(model.data.UserID)
		q.AppendSQL(",")
		q.AppendPlaceholder()
		q.AppendArgs(model.data.SeenAt)
		q.AppendSQL(")")

	}

	q.AppendSQL(sqlUpdateMultiTailSeen)

	return q
}

func (dao SeenDAO) UpdateMulti(ctx context.Context, records []SeenRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "")
	q := queryUpdateMultiSeen(records)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)

	if err == nil {
		for i := range records {
			records[i].reset()
		}
	}

	return err
}

func (model *SeenRecord) queryFullUpdate() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlFullUpdateSeen+" WHERE user_id=$2",
		[]any{model.data.SeenAt, model.data.UserID},
		[]any{},
	)
}

func (dao SeenDAO) FullUpdate(ctx context.Context, data *SeenRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "")
	q := data.queryFullUpdate()
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err == nil && ct.RowsAffected() == 0 {
		err = sql.ErrNoRows
	}

	if err == nil {
		data.reset()
	}

	return err
}

func (model *SeenRecord) queryUpdate() *advpg.QueryBuilder {
	if model.updateMask == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE seen SET`)
	if model.updateMask&1 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" seen_at=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.SeenAt)
	}
	q.AppendSQL(` WHERE user_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.UserID)

	return q
}

func (model *SeenRecord) reset() {
	model.updateMask = 0
}
func (dao SeenDAO) Update(ctx context.Context, data *SeenRecord) error {
	q := data.queryUpdate()
	query := q.SQL()
	if query == "" {
		return nil
	}
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "")

	ct, err := dao.db.Exec(ctx, query, q.Args()...)
	if err == nil && ct.RowsAffected() == 0 {
		err = sql.ErrNoRows
	}
	if err == nil {
		data.reset()
	}

	return err
}
func (model *SeenRecord) queryDelete() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlDeleteSeen,
		[]any{model.data.UserID},
		nil,
	)
}

func (dao SeenDAO) Delete(ctx context.Context, data *SeenRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "")
	q := data.queryDelete()
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func queryDeleteMultiSeen(models []SeenRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(sqlDeleteMultiHeadSeen)

	for i, model := range models {
		if i > 0 {
			q.AppendSQL(",")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.UserID)
	}

	q.AppendSQL(")")
	return q
}

func (dao SeenDAO) DeleteMulti(ctx context.Context, records []SeenRecord) error {
	if len(records) == 0 {
		return nil
	}

	ctx = advpgconn.QueryInfoCtx(ctx, "seen", "")
	q := queryDeleteMultiSeen(records)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

//// User ////

const (
	sqlSelectUser          = `SELECT id, name, type, post_count, created_at, updated_at FROM users`
	sqlInsertHeadUser      = `INSERT INTO users (name, type) VALUES `
	sqlInsertTailUser      = ` RETURNING id, post_count, created_at, updated_at`
	sqlInsertUser          = sqlInsertHeadUser + `($1, $2)` + sqlInsertTailUser
	sqlFullUpdateUser      = `UPDATE users SET name=$1, type=$2, post_count=post_count+$3`
	sqlUpdateReturningUser = ` RETURNING post_count, updated_at`
	sqlUpdateMultiHeadUser = `UPDATE users SET name=(t::users).name, type=(t::users).type, post_count=users.post_count+(t::users).post_count FROM (VALUES `
	sqlUpdateMultiTailUser = `) t WHERE users.id=(t::users).id RETURNING users.post_count, users.updated_at`
	sqlSelectMutatorsUser  = `SELECT post_count FROM users WHERE id=$1`

	sqlDeleteUser          = `DELETE FROM users WHERE id=$1`
	sqlDeleteMultiHeadUser = `DELETE FROM users WHERE id IN (`
)

type UserRecord struct {
	updateMask   uint64
	data         User
	mutPostCount int
}

func (data User) Record() *UserRecord {
	return &UserRecord{data: data}
}

func (model *UserRecord) ID() int {
	return model.data.ID
}

func (model *UserRecord) Name() string {
	return model.data.Name
}

func (model *UserRecord) Type() int {
	return model.data.Type
}

func (model *UserRecord) PostCount() int {
	return model.data.PostCount
}

func (model *UserRecord) CreatedAt() time.Time {
	return model.data.CreatedAt
}

func (model *UserRecord) UpdatedAt() time.Time {
	return model.data.UpdatedAt
}

func (model *UserRecord) SetName(x string) {
	model.data.Name = x
	model.updateMask |= 1
}

func (model *UserRecord) SetType(x int) {
	model.data.Type = x
	model.updateMask |= 2
}

func (model *UserRecord) IncPostCount() {
	model.mutPostCount++
}

func (model *UserRecord) DecPostCount() {
	model.mutPostCount--
}

func (model *UserRecord) AddPostCount(x int) {
	model.mutPostCount += x
}

func (*UserRecord) Table() string {
	return "users"
}

type UserDAO struct {
	db advpg.DB
}

func NewUserDAO(db advpg.DB) UserDAO {
	return UserDAO{db: db}
}

func (model *UserRecord) querySelectByID(inID int, limit, offset uint) *advpg.SimpleQuery {
	sql := sqlSelectUser + ` WHERE id=$1`
	if limit > 0 {
		sql += " LIMIT " + strconv.FormatUint(uint64(limit), 10)
	}
	if offset > 0 {
		sql += " OFFSET " + strconv.FormatUint(uint64(offset), 10)
	}
	return advpg.NewSimpleQuery(
		sql,
		[]any{inID},
		[]any{&model.data.ID, &model.data.Name, &model.data.Type, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt},
	)
}

func (model *UserRecord) queryDeleteByID(inID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM users WHERE id=$1`,
		[]any{inID},
		nil,
	)
}

func (dao UserDAO) SelectByID(ctx context.Context, inID int, optFuncs ...advpg.SelectOptionFunc) (UserRecord, error) {
	var data UserRecord
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "ID")
	opt := advpg.NewSelectOptions(optFuncs...)
	limit := opt.Limit()
	q := data.querySelectByID(inID, limit, opt.Offset())
	db := advpgconn.ReplicaByOpt(dao.db, opt, "users")
	row := db.QueryRow(ctx, q.SQL(), q.Args()...)
	err := row.Scan(q.Results()...)

	return data, err
}

func (dao UserDAO) DeleteByID(ctx context.Context, inID int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "ID")
	q := (*UserRecord)(nil).queryDeleteByID(inID)
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

type SelectMultiByIDTypeKey struct {
	ID   int
	Type int
}

func (model *UserRecord) querySelectMultiByIDType(keys []SelectMultiByIDTypeKey, limit, offset uint) *advpg.QueryBuilder {
	if len(keys) == 0 {
		return &advpg.QueryBuilder{}

	}

	q := advpg.NewQueryBuilder(sqlSelectUser + ` WHERE (id, type) IN (`)

	for i, k := range keys {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.ID)
		q.AppendSQL(", $")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.Type)
		q.AppendSQL(")")
	}

	q.AppendSQL(`) ORDER BY created_at DESC`)
	if limit > 0 {
		q.AppendSQL(" LIMIT " + strconv.FormatUint(uint64(limit), 10))
	}
	if offset > 0 {
		q.AppendSQL(" OFFSET " + strconv.FormatUint(uint64(offset), 10))
	}
	q.SetResults([]any{&model.data.ID, &model.data.Name, &model.data.Type, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt})

	return q
}

func (model *UserRecord) queryDeleteMultiByIDType(keys []SelectMultiByIDTypeKey) *advpg.QueryBuilder {
	if len(keys) == 0 {
		return &advpg.QueryBuilder{}

	}

	q := advpg.NewQueryBuilder(`DELETE FROM users WHERE (id, type) IN (`)

	for i, k := range keys {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.ID)
		q.AppendSQL(", $")
		q.AppendPlaceholderNum()
		q.AppendArgs(k.Type)
		q.AppendSQL(")")
	}

	q.AppendSQL(`)`)

	return q
}

func (dao UserDAO) SelectMultiByIDType(ctx context.Context, keys []SelectMultiByIDTypeKey, optFuncs ...advpg.SelectOptionFunc) ([]UserRecord, error) {
	var data UserRecord
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "IDType")
	opt := advpg.NewSelectOptions(optFuncs...)
	limit := opt.Limit()
	q := data.querySelectMultiByIDType(keys, limit, opt.Offset())
	db := advpgconn.ReplicaByOpt(dao.db, opt, "users")

	rows, err := db.Query(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	ret := ([]UserRecord)(nil)

	for rows.Next() {
		if err = rows.Scan(q.Results()...); err != nil {
			return nil, err
		}

		ret = append(ret, data)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return ret, nil
}

func (dao UserDAO) DeleteMultiByIDType(ctx context.Context, keys []SelectMultiByIDTypeKey) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "IDType")
	q := (*UserRecord)(nil).queryDeleteMultiByIDType(keys)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

func (model *UserRecord) querySelectByName(inName string, limit, offset uint) *advpg.SimpleQuery {
	sql := sqlSelectUser + ` WHERE name=$1`
	if limit > 0 {
		sql += " LIMIT " + strconv.FormatUint(uint64(limit), 10)
	}
	if offset > 0 {
		sql += " OFFSET " + strconv.FormatUint(uint64(offset), 10)
	}
	return advpg.NewSimpleQuery(
		sql,
		[]any{inName},
		[]any{&model.data.ID, &model.data.Name, &model.data.Type, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt},
	)
}

func (model *UserRecord) queryDeleteByName(inName string) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM users WHERE name=$1`,
		[]any{inName},
		nil,
	)
}

func (dao UserDAO) SelectByName(ctx context.Context, inName string, optFuncs ...advpg.SelectOptionFunc) ([]UserRecord, error) {
	var data UserRecord
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "Name")
	opt := advpg.NewSelectOptions(optFuncs...)
	limit := opt.Limit()
	q := data.querySelectByName(inName, limit, opt.Offset())
	db := advpgconn.ReplicaByOpt(dao.db, opt, "users")

	rows, err := db.Query(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	ret := ([]UserRecord)(nil)

	for rows.Next() {
		if err = rows.Scan(q.Results()...); err != nil {
			return nil, err
		}

		ret = append(ret, data)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return ret, nil
}

func (dao UserDAO) DeleteByName(ctx context.Context, inName string) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "Name")
	q := (*UserRecord)(nil).queryDeleteByName(inName)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

func (model *UserRecord) queryInsert() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlInsertUser,
		[]any{model.data.Name, model.data.Type},
		[]any{&model.data.ID, &model.data.PostCount, &model.data.CreatedAt, &model.data.UpdatedAt},
	)
}

func (dao UserDAO) Insert(ctx context.Context, data *UserRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "")
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)

	if err == nil {
		data.reset()
	}

	return err
}

func queryInsertMultiUser(models []UserRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilderCap(sqlInsertHeadUser, 2*len(models), 4*len(models))

	for i, model := range models {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}

		q.AppendPlaceholder()
		q.AppendArgs(model.data.Name)
		q.AppendSQL(",")

		q.AppendPlaceholder()
		q.AppendArgs(model.data.Type)
		q.AppendSQL(")")

		q.AppendResults(&models[i].data.ID, &models[i].data.PostCount, &models[i].data.CreatedAt, &models[i].data.UpdatedAt)
	}

	q.AppendSQL(sqlInsertTailUser)

	return q
}

func (dao UserDAO) InsertMulti(ctx context.Context, records []UserRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "")
	q := queryInsertMultiUser(records)
	rows, err := dao.db.Query(ctx, q.SQL(), q.Args()...)
	defer rows.Close()

	if err == nil {
		results := q.Results()
		from := 0
		to := 4

		for rows.Next() {
			if err = rows.Scan(results[from:to]...); err != nil {
				break
			}

			from = to
			to += 4
		}

		if err == nil {
			err = rows.Err()
		}

		if from < len(results) {
			err = fmt.Errorf("UserDAO.InsertMulti: got %d records, but %d was expected", from/4, len(results)/4)
		}
	}

	if err == nil {
		for i := range records {
			records[i].reset()
		}
	}

	return err
}

func queryUpdateMultiUser(models []UserRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilderCap(sqlUpdateMultiHeadUser, 4*len(models), 2*len(models))

	for i, model := range models {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}

		q.AppendPlaceholder()
		q.AppendArgs(model.data.ID)
		q.AppendSQL(",")
		q.AppendPlaceholder()
		q.AppendArgs(model.data.Name)
		q.AppendSQL(",")
		q.AppendPlaceholder()
		q.AppendArgs(model.data.Type)
		q.AppendSQL(",")
		q.AppendPlaceholder()
		q.AppendArgs(model.mutPostCount)
		q.AppendSQL(",")
		q.AppendSQL("NULL")
		q.AppendSQL(",")
		q.AppendSQL("NULL")
		q.AppendSQL(")")

		q.AppendResults(&models[i].data.PostCount, &models[i].data.UpdatedAt)
	}

	q.AppendSQL(sqlUpdateMultiTailUser)

	return q
}

func (dao UserDAO) UpdateMulti(ctx context.Context, records []UserRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "")
	q := queryUpdateMultiUser(records)
	rows, err := dao.db.Query(ctx, q.SQL(), q.Args()...)
	defer rows.Close()

	if err == nil {
		results := q.Results()
		from := 0
		to := 2

		for rows.Next() {
			if err = rows.Scan(results[from:to]...); err != nil {
				break
			}

			from = to
			to += 2
		}

		if err == nil {
			err = rows.Err()
		}

		if from < len(results) {
			err = fmt.Errorf("UserDAO.UpdateMulti: got %d records, but %d was expected", from/2, len(results)/2)
		}
	}

	if err == nil {
		for i := range records {
			records[i].reset()
		}
	}

	return err
}

func (model *UserRecord) queryFullUpdate() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlFullUpdateUser+" WHERE id=$4"+sqlUpdateReturningUser,
		[]any{model.data.Name, model.data.Type, model.mutPostCount, model.data.ID},
		[]any{&model.data.PostCount, &model.data.UpdatedAt},
	)
}

func (dao UserDAO) FullUpdate(ctx context.Context, data *UserRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "")
	q := data.queryFullUpdate()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)

	if err == nil {
		data.reset()
	}

	return err
}

func (model *UserRecord) queryUpdate() *advpg.QueryBuilder {
	if model.updateMask == 0 && model.mutPostCount == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE users SET`)
	if model.updateMask&1 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" name=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Name)
	}
	if model.updateMask&2 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" type=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Type)
	}
	if model.mutPostCount != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" post_count=post_count+$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.mutPostCount)
	}
	q.AppendSQL(` WHERE id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.ID)

	q.AppendSQL(sqlUpdateReturningUser)
	q.SetResults([]any{&model.data.PostCount, &model.data.UpdatedAt})

	return q
}

func (model *UserRecord) querySelectMutators() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectMutatorsUser,
		[]any{model.data.ID},
		[]any{&model.data.PostCount},
	)
}

func (model *UserRecord) reset() {
	model.updateMask = 0
	model.mutPostCount = 0
}
func (dao UserDAO) Update(ctx context.Context, data *UserRecord) error {
	q := advpg.Query(data.queryUpdate())
	index := ""
	query := q.SQL()
	if query == "" {
		q = data.querySelectMutators()
		query = q.SQL()
		index = "ID"
	}
	ctx = advpgconn.QueryInfoCtx(ctx, "users", index)

	err := dao.db.QueryRow(ctx, query, q.Args()...).Scan(q.Results()...)
	if err == nil {
		data.reset()
	}

	return err
}
func (model *UserRecord) queryDelete() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlDeleteUser,
		[]any{model.data.ID},
		nil,
	)
}

func (dao UserDAO) Delete(ctx context.Context, data *UserRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "users", "")
	q := data.queryDelete()
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func queryDeleteMultiUser(models []UserRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(sqlDeleteMultiHeadUser)

	for i, model := range models {
		if i > 0 {
			q.AppendSQL(",")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.ID)
	}

	q.AppendSQL(")")
	return q
}

func (dao UserDAO) DeleteMulti(ctx context.Context, records []UserRecord) error {
	if len(records) == 0 {
		return nil
	}

	ctx = advpgconn.QueryInfoCtx(ctx, "users", "")
	q := queryDeleteMultiUser(records)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

//// UserOptions ////

const (
	sqlSelectUserOptions          = `SELECT user_id, option_id, flag, option FROM user_options`
	sqlInsertHeadUserOptions      = `INSERT INTO user_options (user_id, option_id, flag) VALUES `
	sqlInsertTailUserOptions      = ` ON CONFLICT (user_id, option_id) DO UPDATE SET flag=EXCLUDED.flag, option=EXCLUDED.option RETURNING option`
	sqlInsertUserOptions          = sqlInsertHeadUserOptions + `($1, $2, $3)` + sqlInsertTailUserOptions
	sqlFullUpdateUserOptions      = `UPDATE user_options SET flag=$1, option=$2`
	sqlUpdateMultiHeadUserOptions = `UPDATE user_options SET flag=(t::user_options).flag, option=(t::user_options).option FROM (VALUES `
	sqlUpdateMultiTailUserOptions = `) t WHERE user_options.user_id=(t::user_options).user_id AND user_options.option_id=(t::user_options).option_id`
	sqlDeleteUserOptions          = `DELETE FROM user_options WHERE user_id=$1 AND option_id=$2`
	sqlDeleteMultiHeadUserOptions = `DELETE FROM user_options WHERE (user_id, option_id) IN (`
)

type UserOptionsRecord struct {
	updateMask uint64
	data       UserOptions
}

func (data UserOptions) Record() *UserOptionsRecord {
	return &UserOptionsRecord{data: data}
}

func (model *UserOptionsRecord) UserID() int {
	return model.data.UserID
}

func (model *UserOptionsRecord) OptionID() int {
	return model.data.OptionID
}

func (model *UserOptionsRecord) Flag() bool {
	return model.data.Flag
}

func (model *UserOptionsRecord) Option() string {
	return model.data.Option
}

func (model *UserOptionsRecord) SetUserID(x int) {
	model.data.UserID = x
}

func (model *UserOptionsRecord) SetOptionID(x int) {
	model.data.OptionID = x
}

func (model *UserOptionsRecord) SetFlag(x bool) {
	model.data.Flag = x
	model.updateMask |= 1
}

func (model *UserOptionsRecord) SetOption(x string) {
	model.data.Option = x
	model.updateMask |= 2
}

func (*UserOptionsRecord) Table() string {
	return "user_options"
}

type UserOptionsDAO struct {
	db advpg.DB
}

func NewUserOptionsDAO(db advpg.DB) UserOptionsDAO {
	return UserOptionsDAO{db: db}
}

func (model *UserOptionsRecord) querySelectByPrimaryKey(inUserID int, inOptionID int, limit, offset uint) *advpg.SimpleQuery {
	sql := sqlSelectUserOptions + ` WHERE user_id=$1 AND option_id=$2`
	if limit > 0 {
		sql += " LIMIT " + strconv.FormatUint(uint64(limit), 10)
	}
	if offset > 0 {
		sql += " OFFSET " + strconv.FormatUint(uint64(offset), 10)
	}
	return advpg.NewSimpleQuery(
		sql,
		[]any{inUserID, inOptionID},
		[]any{&model.data.UserID, &model.data.OptionID, &model.data.Flag, &model.data.Option},
	)
}

func (model *UserOptionsRecord) queryDeleteByPrimaryKey(inUserID int, inOptionID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM user_options WHERE user_id=$1 AND option_id=$2`,
		[]any{inUserID, inOptionID},
		nil,
	)
}

func (dao UserOptionsDAO) SelectByPrimaryKey(ctx context.Context, inUserID int, inOptionID int, optFuncs ...advpg.SelectOptionFunc) (UserOptionsRecord, error) {
	var data UserOptionsRecord
	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "PrimaryKey")
	opt := advpg.NewSelectOptions(optFuncs...)
	limit := opt.Limit()
	q := data.querySelectByPrimaryKey(inUserID, inOptionID, limit, opt.Offset())
	db := advpgconn.ReplicaByOpt(dao.db, opt, "user_options")
	row := db.QueryRow(ctx, q.SQL(), q.Args()...)
	err := row.Scan(q.Results()...)

	return data, err
}

func (dao UserOptionsDAO) DeleteByPrimaryKey(ctx context.Context, inUserID int, inOptionID int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "PrimaryKey")
	q := (*UserOptionsRecord)(nil).queryDeleteByPrimaryKey(inUserID, inOptionID)
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *UserOptionsRecord) querySelectByUserID(inUserID int, limit, offset uint) *advpg.SimpleQuery {
	sql := sqlSelectUserOptions + ` WHERE user_id=$1 ORDER BY option_id`
	if limit > 0 {
		sql += " LIMIT " + strconv.FormatUint(uint64(limit), 10)
	}
	if offset > 0 {
		sql += " OFFSET " + strconv.FormatUint(uint64(offset), 10)
	}
	return advpg.NewSimpleQuery(
		sql,
		[]any{inUserID},
		[]any{&model.data.UserID, &model.data.OptionID, &model.data.Flag, &model.data.Option},
	)
}

func (model *UserOptionsRecord) queryDeleteByUserID(inUserID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM user_options WHERE user_id=$1`,
		[]any{inUserID},
		nil,
	)
}

func (dao UserOptionsDAO) SelectByUserID(ctx context.Context, inUserID int, optFuncs ...advpg.SelectOptionFunc) ([]UserOptionsRecord, error) {
	var data UserOptionsRecord
	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "UserID")
	opt := advpg.NewSelectOptions(optFuncs...)
	limit := opt.Limit()
	if limit == 0 {
		limit = 50
	}
	q := data.querySelectByUserID(inUserID, limit, opt.Offset())
	db := advpgconn.ReplicaByOpt(dao.db, opt, "user_options")

	rows, err := db.Query(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	ret := ([]UserOptionsRecord)(nil)

	for rows.Next() {
		if err = rows.Scan(q.Results()...); err != nil {
			return nil, err
		}

		ret = append(ret, data)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return ret, nil
}

func (dao UserOptionsDAO) DeleteByUserID(ctx context.Context, inUserID int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "UserID")
	q := (*UserOptionsRecord)(nil).queryDeleteByUserID(inUserID)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

func (model *UserOptionsRecord) queryInsert() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlInsertUserOptions,
		[]any{model.data.UserID, model.data.OptionID, model.data.Flag},
		[]any{&model.data.Option},
	)
}

func (dao UserOptionsDAO) Insert(ctx context.Context, data *UserOptionsRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "")
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)

	if err == nil {
		data.reset()
	}

	return err
}

func queryInsertMultiUserOptions(models []UserOptionsRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilderCap(sqlInsertHeadUserOptions, 3*len(models), 1*len(models))

	for i, model := range models {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}

		q.AppendPlaceholder()
		q.AppendArgs(model.data.UserID)
		q.AppendSQL(",")

		q.AppendPlaceholder()
		q.AppendArgs(model.data.OptionID)
		q.AppendSQL(",")

		q.AppendPlaceholder()
		q.AppendArgs(model.data.Flag)
		q.AppendSQL(")")

		q.AppendResults(&models[i].data.Option)
	}

	q.AppendSQL(sqlInsertTailUserOptions)

	return q
}

func (dao UserOptionsDAO) InsertMulti(ctx context.Context, records []UserOptionsRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "")
	q := queryInsertMultiUserOptions(records)
	rows, err := dao.db.Query(ctx, q.SQL(), q.Args()...)
	defer rows.Close()

	if err == nil {
		results := q.Results()
		from := 0
		to := 1

		for rows.Next() {
			if err = rows.Scan(results[from:to]...); err != nil {
				break
			}

			from = to
			to += 1
		}

		if err == nil {
			err = rows.Err()
		}

		if from < len(results) {
			err = fmt.Errorf("UserOptionsDAO.InsertMulti: got %d records, but %d was expected", from/1, len(results)/1)
		}
	}

	if err == nil {
		for i := range records {
			records[i].reset()
		}
	}

	return err
}

func queryUpdateMultiUserOptions(models []UserOptionsRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilderCap(sqlUpdateMultiHeadUserOptions, 4*len(models), 0)

	for i, model := range models {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}

		q.AppendPlaceholder()
		q.AppendArgs(model.data.UserID)
		q.AppendSQL(",")
		q.AppendPlaceholder()
		q.AppendArgs(model.data.OptionID)
		q.AppendSQL(",")
		q.AppendPlaceholder()
		q.AppendArgs(model.data.Flag)
		q.AppendSQL(",")
		q.AppendPlaceholder()
		q.AppendArgs(model.data.Option)
		q.AppendSQL(")")

	}

	q.AppendSQL(sqlUpdateMultiTailUserOptions)

	return q
}

func (dao UserOptionsDAO) UpdateMulti(ctx context.Context, records []UserOptionsRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "")
	q := queryUpdateMultiUserOptions(records)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)

	if err == nil {
		for i := range records {
			records[i].reset()
		}
	}

	return err
}

func (model *UserOptionsRecord) queryFullUpdate() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlFullUpdateUserOptions+" WHERE user_id=$3 AND option_id=$4",
		[]any{model.data.Flag, model.data.Option, model.data.UserID, model.data.OptionID},
		[]any{},
	)
}

func (dao UserOptionsDAO) FullUpdate(ctx context.Context, data *UserOptionsRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "")
	q := data.queryFullUpdate()
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err == nil && ct.RowsAffected() == 0 {
		err = sql.ErrNoRows
	}

	if err == nil {
		data.reset()
	}

	return err
}

func (model *UserOptionsRecord) queryUpdate() *advpg.QueryBuilder {
	if model.updateMask == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE user_options SET`)
	if model.updateMask&1 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" flag=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Flag)
	}
	if model.updateMask&2 != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" option=$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.Option)
	}
	q.AppendSQL(` WHERE user_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.UserID)
	q.AppendSQL(` AND option_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.OptionID)

	return q
}

func (model *UserOptionsRecord) reset() {
	model.updateMask = 0
}
func (dao UserOptionsDAO) Update(ctx context.Context, data *UserOptionsRecord) error {
	q := data.queryUpdate()
	query := q.SQL()
	if query == "" {
		return nil
	}
	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "")

	ct, err := dao.db.Exec(ctx, query, q.Args()...)
	if err == nil && ct.RowsAffected() == 0 {
		err = sql.ErrNoRows
	}
	if err == nil {
		data.reset()
	}

	return err
}
func (model *UserOptionsRecord) queryDelete() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlDeleteUserOptions,
		[]any{model.data.UserID, model.data.OptionID},
		nil,
	)
}

func (dao UserOptionsDAO) Delete(ctx context.Context, data *UserOptionsRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "")
	q := data.queryDelete()
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func queryDeleteMultiUserOptions(models []UserOptionsRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(sqlDeleteMultiHeadUserOptions)

	for i, model := range models {
		if i == 0 {
			q.AppendSQL("(")
		} else {
			q.AppendSQL(",(")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.UserID)
		q.AppendSQL(", $")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.OptionID)
		q.AppendSQL(")")
	}

	q.AppendSQL(")")
	return q
}

func (dao UserOptionsDAO) DeleteMulti(ctx context.Context, records []UserOptionsRecord) error {
	if len(records) == 0 {
		return nil
	}

	ctx = advpgconn.QueryInfoCtx(ctx, "user_options", "")
	q := queryDeleteMultiUserOptions(records)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}

//// UserViews ////

const (
	sqlSelectUserViews          = `SELECT user_id, views FROM user_views`
	sqlInsertHeadUserViews      = `INSERT INTO user_views (user_id, views) VALUES `
	sqlInsertTailUserViews      = ` ON CONFLICT (user_id) DO UPDATE SET views=user_views.views+$3 RETURNING views`
	sqlInsertUserViews          = sqlInsertHeadUserViews + `($1, $2)` + sqlInsertTailUserViews
	sqlUpdateReturningUserViews = ` RETURNING views`
	sqlSelectMutatorsUserViews  = `SELECT views FROM user_views WHERE user_id=$1`

	sqlDeleteUserViews          = `DELETE FROM user_views WHERE user_id=$1`
	sqlDeleteMultiHeadUserViews = `DELETE FROM user_views WHERE user_id IN (`
)

type UserViewsRecord struct {
	data     UserViews
	mutViews int
}

func (data UserViews) Record() *UserViewsRecord {
	return &UserViewsRecord{data: data}
}

func (model *UserViewsRecord) UserID() int {
	return model.data.UserID
}

func (model *UserViewsRecord) Views() int {
	return model.data.Views
}

func (model *UserViewsRecord) SetUserID(x int) {
	model.data.UserID = x
}

func (model *UserViewsRecord) IncViews() {
	model.mutViews++
}

func (model *UserViewsRecord) DecViews() {
	model.mutViews--
}

func (model *UserViewsRecord) AddViews(x int) {
	model.mutViews += x
}

func (*UserViewsRecord) Table() string {
	return "user_views"
}

type UserViewsDAO struct {
	db advpg.DB
}

func NewUserViewsDAO(db advpg.DB) UserViewsDAO {
	return UserViewsDAO{db: db}
}

func (model *UserViewsRecord) querySelectByUserID(inUserID int, limit, offset uint) *advpg.SimpleQuery {
	sql := sqlSelectUserViews + ` WHERE user_id=$1`
	if limit > 0 {
		sql += " LIMIT " + strconv.FormatUint(uint64(limit), 10)
	}
	if offset > 0 {
		sql += " OFFSET " + strconv.FormatUint(uint64(offset), 10)
	}
	return advpg.NewSimpleQuery(
		sql,
		[]any{inUserID},
		[]any{&model.data.UserID, &model.data.Views},
	)
}

func (model *UserViewsRecord) queryDeleteByUserID(inUserID int) *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		`DELETE FROM user_views WHERE user_id=$1`,
		[]any{inUserID},
		nil,
	)
}

func (dao UserViewsDAO) SelectByUserID(ctx context.Context, inUserID int, optFuncs ...advpg.SelectOptionFunc) (UserViewsRecord, error) {
	var data UserViewsRecord
	ctx = advpgconn.QueryInfoCtx(ctx, "user_views", "UserID")
	opt := advpg.NewSelectOptions(optFuncs...)
	limit := opt.Limit()
	q := data.querySelectByUserID(inUserID, limit, opt.Offset())
	db := advpgconn.ReplicaByOpt(dao.db, opt, "user_views")
	row := db.QueryRow(ctx, q.SQL(), q.Args()...)
	err := row.Scan(q.Results()...)

	return data, err
}

func (dao UserViewsDAO) DeleteByUserID(ctx context.Context, inUserID int) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_views", "UserID")
	q := (*UserViewsRecord)(nil).queryDeleteByUserID(inUserID)
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (model *UserViewsRecord) queryInsert() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlInsertUserViews,
		[]any{model.data.UserID, model.data.Views + model.mutViews, model.mutViews},
		[]any{&model.data.Views},
	)
}

func (dao UserViewsDAO) Insert(ctx context.Context, data *UserViewsRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_views", "")
	q := data.queryInsert()
	err := dao.db.QueryRow(ctx, q.SQL(), q.Args()...).Scan(q.Results()...)

	if err == nil {
		data.reset()
	}

	return err
}

func (model *UserViewsRecord) queryUpdate() *advpg.QueryBuilder {
	if model.mutViews == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(`UPDATE user_views SET`)
	if model.mutViews != 0 {
		if len(q.Args()) != 0 {
			q.AppendSQL(",")
		}

		q.AppendSQL(" views=views+$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.mutViews)
	}
	q.AppendSQL(` WHERE user_id=$`)
	q.AppendPlaceholderNum()
	q.AppendArgs(model.data.UserID)

	q.AppendSQL(sqlUpdateReturningUserViews)
	q.SetResults([]any{&model.data.Views})

	return q
}

func (model *UserViewsRecord) querySelectMutators() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlSelectMutatorsUserViews,
		[]any{model.data.UserID},
		[]any{&model.data.Views},
	)
}

func (model *UserViewsRecord) reset() {
	model.mutViews = 0
}
func (dao UserViewsDAO) Update(ctx context.Context, data *UserViewsRecord) error {
	q := advpg.Query(data.queryUpdate())
	index := ""
	query := q.SQL()
	if query == "" {
		q = data.querySelectMutators()
		query = q.SQL()
		index = "UserID"
	}
	ctx = advpgconn.QueryInfoCtx(ctx, "user_views", index)

	err := dao.db.QueryRow(ctx, query, q.Args()...).Scan(q.Results()...)
	if err == nil {
		data.reset()
	}

	return err
}
func (model *UserViewsRecord) queryDelete() *advpg.SimpleQuery {
	return advpg.NewSimpleQuery(
		sqlDeleteUserViews,
		[]any{model.data.UserID},
		nil,
	)
}

func (dao UserViewsDAO) Delete(ctx context.Context, data *UserViewsRecord) error {
	ctx = advpgconn.QueryInfoCtx(ctx, "user_views", "")
	q := data.queryDelete()
	ct, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	if err != nil {
		return err
	}

	if ct.RowsAffected() == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func queryDeleteMultiUserViews(models []UserViewsRecord) *advpg.QueryBuilder {
	if len(models) == 0 {
		return &advpg.QueryBuilder{}
	}

	q := advpg.NewQueryBuilder(sqlDeleteMultiHeadUserViews)

	for i, model := range models {
		if i > 0 {
			q.AppendSQL(",")
		}
		q.AppendSQL("$")
		q.AppendPlaceholderNum()
		q.AppendArgs(model.data.UserID)
	}

	q.AppendSQL(")")
	return q
}

func (dao UserViewsDAO) DeleteMulti(ctx context.Context, records []UserViewsRecord) error {
	if len(records) == 0 {
		return nil
	}

	ctx = advpgconn.QueryInfoCtx(ctx, "user_views", "")
	q := queryDeleteMultiUserViews(records)
	_, err := dao.db.Exec(ctx, q.SQL(), q.Args()...)
	return err
}
